import json
import os

# Path to the summary generated by the other script
# Updated to match the OUTPUT_DIR in your signals script
SUMMARY_PATH = "reports/crypto-cta-signals/summary.json"

def generate_index():
    try:
        if not os.path.exists(SUMMARY_PATH):
            print(f"Error: {SUMMARY_PATH} not found. Ensure the signal script runs first.")
            return

        with open(SUMMARY_PATH, 'r') as f:
            all_summaries = json.load(f)
            
        # These keys now match the dictionary structure in generate_crypto_cta_signals.py
        fast_data = all_summaries.get('fast', {})
        slow_data = all_summaries.get('slow', {})
        
        fast_positions = fast_data.get('latest_positions', {})
        
        html_content = f"""
        <html>
        <head>
            <title>Crypto CTA Signals</title>
            <link rel="stylesheet" href="../../styles.css">
        </head>
        <body>
            <h1>Crypto CTA Positioning</h1>
            <p><b>Last Updated:</b> {fast_data.get('generated_at', 'N/A')}</p>
            <p><b>Model:</b> Fast (20/50/100 Day MAs)</p>
            
            <table border="1">
                <tr>
                    <th>Asset</th>
                    <th>Position (-50 to +50)</th>
                </tr>
        """
        
        for symbol, pos in fast_positions.items():
            html_content += f"<tr><td>{symbol}</td><td>{pos}</td></tr>"
            
        html_content += """
            </table>
        </body>
        </html>
        """

        with open('index.html', 'w') as f:
            f.write(html_content)
        print("Successfully generated index.html")

    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    generate_index()
